# Generated by Django 6.0.2 on 2026-03-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CPF', max_length=4)),
                ('documento', models.CharField(help_text='Armazene sem máscara (apenas números).', max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('endereco', models.CharField(blank=True, max_length=160)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=160)),
                ('bairro', models.CharField(blank=True, max_length=160)),
                ('cidade', models.CharField(blank=True, max_length=160)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nome'], name='clientes_cl_nome_b2cdde_idx'), models.Index(fields=['documento'], name='clientes_cl_documen_76f212_idx'), models.Index(fields=['email'], name='clientes_cl_email_eae461_idx')],
                'constraints': [models.UniqueConstraint(fields=('documento',), name='uniq_cliente_documento')],
            },
        ),
    ]
